package com.jiayusoft.mobile.utils.database;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig binganDaoConfig;
    private final DaoConfig officeDaoConfig;
    private final DaoConfig orgDaoConfig;

    private final BinganDao binganDao;
    private final OfficeDao officeDao;
    private final OrgDao orgDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        binganDaoConfig = daoConfigMap.get(BinganDao.class).clone();
        binganDaoConfig.initIdentityScope(type);

        officeDaoConfig = daoConfigMap.get(OfficeDao.class).clone();
        officeDaoConfig.initIdentityScope(type);

        orgDaoConfig = daoConfigMap.get(OrgDao.class).clone();
        orgDaoConfig.initIdentityScope(type);

        binganDao = new BinganDao(binganDaoConfig, this);
        officeDao = new OfficeDao(officeDaoConfig, this);
        orgDao = new OrgDao(orgDaoConfig, this);

        registerDao(Bingan.class, binganDao);
        registerDao(Office.class, officeDao);
        registerDao(Org.class, orgDao);
    }

    public void clear() {
        binganDaoConfig.getIdentityScope().clear();
        officeDaoConfig.getIdentityScope().clear();
        orgDaoConfig.getIdentityScope().clear();
    }

    public BinganDao getBinganDao() {
        return binganDao;
    }

    public OfficeDao getOfficeDao() {
        return officeDao;
    }

    public OrgDao getOrgDao() {
        return orgDao;
    }

}
