package com.jiayusoft.mobile.utils.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OFFICE.
 */
public class Office {

    private String orgcode;
    private String code;
    private String name;

    public Office() {
    }

    public Office(String orgcode, String code, String name) {
        this.orgcode = orgcode;
        this.code = code;
        this.name = name;
    }

    public String getOrgcode() {
        return orgcode;
    }

    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
